databases:
  - name: wedding-db
    plan: free
    databaseName: wedding_db
    
services:
  - type: web
    name: wedding-invitation
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: wedding-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: wedding-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wedding-db
          property: password
      - key: PORT
        value: 8080
    healthCheckPath: /

